[package]
name = "player_cli"
version = "0.1.0"
authors = ["Gizeta <i@gizeta.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.6", features = ["blocking"] }
rodio = "0.11.0"
